#!/bin/sh
BASE_DIR=$(dirname $(dirname $(realpath $0)))
JSPM_PATH=$(which jspm 2>/dev/null)
if [ "$?" != "0" ] || [ -z "$JSPM_PATH" ]; then
  echo "jspm not found, make sure it is installed."
  exit 1
fi
if [ $(realpath "$JSPM_PATH") = $JSPM_PATH ] && [ -d $(dirname "$JSPM_PATH")/node_modules/jspm ]; then
  JSPM_DIR=$(dirname "$JSPM_PATH")/node_modules/jspm
else
  JSPM_DIR=$(dirname $(dirname $(realpath "$JSPM_PATH")))
fi
if [ -d $JSPM_DIR/node_modules ]; then
  JSPM_LOADER=$JSPM_DIR/node_modules/@jspm/resolve/loader.mjs
else
  echo "jspm loader not found, make sure it is installed."
  exit 1
fi
case "$(uname -s)" in
  CYGWIN*|MINGW32*|MINGW64*)
    JSPM_LOADER=/$(cygpath -w "$JSPM_LOADER")
    BASE_DIR=/$(cygpath -w "$BASE_DIR")
    ;;
  *)
esac
NODE_OPTIONS="--experimental-modules --no-warnings --loader $JSPM_LOADER" node "$BASE_DIR/npm\loose-envify@1.4.0\cli.js" "$@"
ret=$?
exit $ret
